version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGO_CONN_STRING: "mongodb://username:password@mongo:27017"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    command: npm run dev

volumes:
  mongodb_data:
